### ISSUE TITLE
Не соединения с интернетом.

### ISSUE THREAD

**Issue by jagajaga** [serso/android-messengerpp#3]
При открытии приложение говорит, что нет интернета, хотя он есть (wifi). То есть приложению нужно соединение с сетью через оператора.

**Comment by AlexTalker** [comment]
Это самая большая проблема приложения.Я считаю, пока у вас нет в приложениии сети, мессенджер писать бессмысленно.

**Comment by serso** [comment]
У меня работает и в wfif и в 3g сетях. Ошибка соединения может быть вызвана багом в реализации протокола. Попробую в следующий релиз добавить дамп стек трейсов, чтобы нормально диагностировать проблему.

**Comment by AlexTalker** [comment]
p.s. Android 4.1.2, samsung galaxy fame

**Comment by AlexTalker** [comment]
так, в новой версии, похоже, пофиксено.
