### ISSUE TITLE
HTML tags are sent in messages

### ISSUE THREAD

**Issue by serso** [serso/android-messengerpp#38]

**Comment by mazurovEV** [comment]
<p dir="ltr"></p>

<p dir="ltr">--<br>
Sent from <a href="market://details?id=com.my.mail">myMail</a> app for Android<br></p>

<p dir="ltr">&#1074;&#1086;&#1089;&#1082;&#1088;&#1077;&#1089;&#1077;&#1085;&#1100;&#1077;, 15 &#1076;&#1077;&#1082;&#1072;&#1073;&#1088;&#1103; 2013&#1075;., 21:30 +04:00 from Sergey Solovyev &lt;notifications@github.com&gt;:</p>

<p dir="ltr">&#8212;<br>
Reply to this email directly or&nbsp; view it on GitHub .</p>

<p dir="ltr">--<br>
Sent from myMail app for Android</p>

**Comment by serso** [comment]
wut?
