### ISSUE TITLE
Unable to log in to some XMPP accounts (qip, yandex, jabber)

### ISSUE THREAD

**Issue by serso** [serso/android-messengerpp#7]

**Comment by santiago26** [comment]
We need more Connection settings in GUI in order to solve this.
Tested settings listed here in section "Настройки соединения"
http://wiki.qip.ru/QIP_Jabber
http://wiki.qip.ru/Я.Онлайн 
and http://www.jabber.ru/node/238 (it is still actual, as far as I know)

**Comment by serso** [comment]
yandex added

**Comment by serso** [comment]
QIP is working (check 'Remove domain from username' checkbox)

**Comment by serso** [comment]
Jabber works now (check 'Remove domain from username' checkbox)
